import {Kana} from '../kana-interface/kana-interface';

export const HiraganaList: Kana[] = [
  // Hiragana
  {location: 'svgsKana/', fname: '12354', name: 'a', jpn: 'あ'},
  {location: 'svgsKana/', fname: '12356', name: 'i', jpn: 'い'},
  {location: 'svgsKana/', fname: '12358', name: 'u', jpn: 'う'},
  {location: 'svgsKana/', fname: '12360', name: 'e', jpn: 'え'},
  {location: 'svgsKana/', fname: '12362', name: 'o', jpn: 'お'},
  {location: 'svgsKana/', fname: '12363', name: 'ka', jpn: 'か'},
  {location: 'svgsKana/', fname: '12365', name: 'ki', jpn: 'き'},
  {location: 'svgsKana/', fname: '12367', name: 'ku', jpn: 'く'},
  {location: 'svgsKana/', fname: '12369', name: 'ke', jpn: 'け'},
  {location: 'svgsKana/', fname: '12371', name: 'ko', jpn: 'こ'},
  //{location: 'svgsKana/', fname: '12373', name: 'sa', jpn: 'さ'},
  {location: 'svgsKana/', fname: '12375', name: 'shi', jpn: 'し'},
  {location: 'svgsKana/', fname: '12377', name: 'su', jpn: 'す'},
  {location: 'svgsKana/', fname: '12379', name: 'se', jpn: 'せ'},
  {location: 'svgsKana/', fname: '12381', name: 'so', jpn: 'そ'},
  {location: 'svgsKana/', fname: '12383', name: 'ta', jpn: 'た'},
  {location: 'svgsKana/', fname: '12385', name: 'chi', jpn: 'ち'},
  {location: 'svgsKana/', fname: '12388', name: 'tsu', jpn: 'つ'},
  {location: 'svgsKana/', fname: '12390', name: 'te', jpn: 'て'},
  {location: 'svgsKana/', fname: '12392', name: 'to', jpn: 'と'},
  {location: 'svgsKana/', fname: '12394', name: 'na', jpn: 'な'},
  {location: 'svgsKana/', fname: '12395', name: 'ni', jpn: 'に'},
  {location: 'svgsKana/', fname: '12396', name: 'nu', jpn: 'ぬ'},
  {location: 'svgsKana/', fname: '12397', name: 'ne', jpn: 'ね'},
  {location: 'svgsKana/', fname: '12398', name: 'no', jpn: 'の'},
  {location: 'svgsKana/', fname: '12399', name: 'ha', jpn: 'は'},
  {location: 'svgsKana/', fname: '12402', name: 'hi', jpn: 'ひ'},
  {location: 'svgsKana/', fname: '12405', name: 'fu', jpn: 'ふ'},
  {location: 'svgsKana/', fname: '12408', name: 'he', jpn: 'へ'},
  {location: 'svgsKana/', fname: '12411', name: 'ho', jpn: 'ほ'},
  {location: 'svgsKana/', fname: '12414', name: 'ma', jpn: 'ま'},
  {location: 'svgsKana/', fname: '12415', name: 'mi', jpn: 'み'},
  {location: 'svgsKana/', fname: '12416', name: 'mu', jpn: 'む'},
  {location: 'svgsKana/', fname: '12417', name: 'me', jpn: 'め'},
  {location: 'svgsKana/', fname: '12418', name: 'mo', jpn: 'も'},
  {location: 'svgsKana/', fname: '12425', name: 'ra', jpn: 'ら'},
  {location: 'svgsKana/', fname: '12426', name: 'ri', jpn: 'り'},
  {location: 'svgsKana/', fname: '12427', name: 'ru', jpn: 'る'},
  {location: 'svgsKana/', fname: '12428', name: 're', jpn: 'れ'},
  {location: 'svgsKana/', fname: '12429', name: 'ro', jpn: 'ろ'},
  {location: 'svgsKana/', fname: '12420', name: 'ya', jpn: 'や'},
  {location: 'svgsKana/', fname: '12422', name: 'yu', jpn: 'ゆ'},
  {location: 'svgsKana/', fname: '12424', name: 'yo', jpn: 'よ'},
  {location: 'svgsKana/', fname: '12431', name: 'wa', jpn: 'わ'},
  {location: 'svgsKana/', fname: '12434', name: 'wo', jpn: 'を'},
  {location: 'svgsKana/', fname: '12364', name: 'ga', jpn: 'が'},
  //{location: 'svgsKana/', fname: '12366', name: 'gi', jpn: 'ぎ'},
  {location: 'svgsKana/', fname: '12368', name: 'gu', jpn: 'ぐ'},
  {location: 'svgsKana/', fname: '12370', name: 'ge', jpn: 'げ'},
  {location: 'svgsKana/', fname: '12372', name: 'go', jpn: 'ご'},
  {location: 'svgsKana/', fname: '12374', name: 'za', jpn: 'ざ'},
  {location: 'svgsKana/', fname: '12376', name: 'ji', jpn: 'じ'},
  {location: 'svgsKana/', fname: '12378', name: 'zu', jpn: 'ず'},
  {location: 'svgsKana/', fname: '12380', name: 'ze', jpn: 'ぜ'},
  {location: 'svgsKana/', fname: '12382', name: 'zo', jpn: 'ぞ'},
  {location: 'svgsKana/', fname: '12384', name: 'da', jpn: 'だ'},
  {location: 'svgsKana/', fname: '12386', name: 'di', jpn: 'ぢ'},
  {location: 'svgsKana/', fname: '12389', name: 'dzu', jpn: 'づ'},
  {location: 'svgsKana/', fname: '12391', name: 'de', jpn: 'で'},
  {location: 'svgsKana/', fname: '12393', name: 'do', jpn: 'ど'},
  {location: 'svgsKana/', fname: '12400', name: 'ba', jpn: 'ば'},
  {location: 'svgsKana/', fname: '12403', name: 'bi', jpn: 'び'},
  {location: 'svgsKana/', fname: '12406', name: 'bu', jpn: 'ぶ'},
  {location: 'svgsKana/', fname: '12409', name: 'be', jpn: 'べ'},
  {location: 'svgsKana/', fname: '12412', name: 'bo', jpn: 'ぼ'},
  {location: 'svgsKana/', fname: '12401', name: 'pa', jpn: 'ぱ'},
  {location: 'svgsKana/', fname: '12404', name: 'pi', jpn: 'ぴ'},
  {location: 'svgsKana/', fname: '12407', name: 'pu', jpn: 'ぷ'},
  {location: 'svgsKana/', fname: '12410', name: 'pe', jpn: 'ぺ'},
  {location: 'svgsKana/', fname: '12413', name: 'po', jpn: 'ぽ'},
];

export const KatakanaList: Kana[] = [
  // Katakana
  {location: 'svgsKana/', fname: ' ', name: 'a', jpn: 'ア'},
  {location: 'svgsKana/', fname: ' ', name: 'i', jpn: 'イ'},
  {location: 'svgsKana/', fname: ' ', name: 'u', jpn: 'ウ'},
  {location: 'svgsKana/', fname: ' ', name: 'e', jpn: 'エ'},
  {location: 'svgsKana/', fname: ' ', name: 'o', jpn: 'オ'},
  {location: 'svgsKana/', fname: ' ', name: 'ka', jpn: 'カ'},
  {location: 'svgsKana/', fname: ' ', name: 'ki', jpn: 'キ'},
  {location: 'svgsKana/', fname: ' ', name: 'ku', jpn: 'ク'},
  {location: 'svgsKana/', fname: ' ', name: 'ke', jpn: 'ケ'},
  {location: 'svgsKana/', fname: ' ', name: 'ko', jpn: 'コ'},
  {location: 'svgsKana/', fname: ' ', name: 'sa', jpn: 'さ'},
  {location: 'svgsKana/', fname: ' ', name: 'shi', jpn: 'し'},
  {location: 'svgsKana/', fname: ' ', name: 'su', jpn: 'す'},
  {location: 'svgsKana/', fname: ' ', name: 'se', jpn: 'せ'},
  {location: 'svgsKana/', fname: ' ', name: 'so', jpn: 'そ'},
  {location: 'svgsKana/', fname: ' ', name: 'ta', jpn: 'た'},
  {location: 'svgsKana/', fname: ' ', name: 'chi', jpn: 'ち'},
  {location: 'svgsKana/', fname: ' ', name: 'tsu', jpn: 'つ'},
  {location: 'svgsKana/', fname: ' ', name: 'te', jpn: 'て'},
  {location: 'svgsKana/', fname: ' ', name: 'to', jpn: 'と'},
  {location: 'svgsKana/', fname: ' ', name: 'na', jpn: 'な'},
  {location: 'svgsKana/', fname: ' ', name: 'ni', jpn: 'に'},
  {location: 'svgsKana/', fname: ' ', name: 'nu', jpn: 'ぬ'},
  {location: 'svgsKana/', fname: ' ', name: 'ne', jpn: 'ね'},
  {location: 'svgsKana/', fname: ' ', name: 'no', jpn: 'の'},
  {location: 'svgsKana/', fname: ' ', name: 'ha', jpn: 'は'},
  {location: 'svgsKana/', fname: ' ', name: 'hi', jpn: 'ひ'},
  {location: 'svgsKana/', fname: ' ', name: 'fu', jpn: 'ふ'},
  {location: 'svgsKana/', fname: ' ', name: 'he', jpn: 'へ'},
  {location: 'svgsKana/', fname: ' ', name: 'ho', jpn: 'ほ'},
  {location: 'svgsKana/', fname: ' ', name: 'ma', jpn: 'ま'},
  {location: 'svgsKana/', fname: ' ', name: 'mi', jpn: 'み'},
  {location: 'svgsKana/', fname: ' ', name: 'mu', jpn: 'む'},
  {location: 'svgsKana/', fname: ' ', name: 'me', jpn: 'め'},
  {location: 'svgsKana/', fname: ' ', name: 'mo', jpn: 'も'},
  {location: 'svgsKana/', fname: ' ', name: 'ra', jpn: 'ら'},
  {location: 'svgsKana/', fname: ' ', name: 'ri', jpn: 'り'},
  {location: 'svgsKana/', fname: ' ', name: 'ru', jpn: 'る'},
  {location: 'svgsKana/', fname: ' ', name: 're', jpn: 'れ'},
  {location: 'svgsKana/', fname: ' ', name: 'ro', jpn: 'ろ'},
  {location: 'svgsKana/', fname: ' ', name: 'ya', jpn: 'や'},
  {location: 'svgsKana/', fname: ' ', name: 'yu', jpn: 'ゆ'},
  {location: 'svgsKana/', fname: ' ', name: 'yo', jpn: 'よ'},
  {location: 'svgsKana/', fname: ' ', name: 'wa', jpn: 'わ'},
  {location: 'svgsKana/', fname: ' ', name: 'wo', jpn: 'を'},
  {location: 'svgsKana/', fname: ' ', name: 'ga', jpn: 'が'},
  {location: 'svgsKana/', fname: ' ', name: 'gi', jpn: 'ぎ'},
  {location: 'svgsKana/', fname: ' ', name: 'gu', jpn: 'ぐ'},
  {location: 'svgsKana/', fname: ' ', name: 'ge', jpn: 'げ'},
  {location: 'svgsKana/', fname: ' ', name: 'go', jpn: 'ご'},
  {location: 'svgsKana/', fname: ' ', name: 'za', jpn: 'ざ'},
  {location: 'svgsKana/', fname: ' ', name: 'ji', jpn: 'じ'},
  {location: 'svgsKana/', fname: ' ', name: 'zu', jpn: 'ず'},
  {location: 'svgsKana/', fname: ' ', name: 'ze', jpn: 'ぜ'},
  {location: 'svgsKana/', fname: ' ', name: 'zo', jpn: 'ぞ'},
  {location: 'svgsKana/', fname: ' ', name: 'da', jpn: 'だ'},
  {location: 'svgsKana/', fname: ' ', name: 'di', jpn: 'ぢ'},
  {location: 'svgsKana/', fname: ' ', name: 'dzu', jpn: 'づ'},
  {location: 'svgsKana/', fname: ' ', name: 'de', jpn: 'で'},
  {location: 'svgsKana/', fname: ' ', name: 'do', jpn: 'ど'},
  {location: 'svgsKana/', fname: ' ', name: 'ba', jpn: 'ば'},
  {location: 'svgsKana/', fname: ' ', name: 'bi', jpn: 'び'},
  {location: 'svgsKana/', fname: ' ', name: 'bu', jpn: 'ぶ'},
  {location: 'svgsKana/', fname: ' ', name: 'be', jpn: 'べ'},
  {location: 'svgsKana/', fname: ' ', name: 'bo', jpn: 'ぼ'},
  {location: 'svgsKana/', fname: ' ', name: 'pa', jpn: 'ぱ'},
  {location: 'svgsKana/', fname: ' ', name: 'pi', jpn: 'ぴ'},
  {location: 'svgsKana/', fname: ' ', name: 'pu', jpn: 'ぷ'},
  {location: 'svgsKana/', fname: ' ', name: 'pe', jpn: 'ぺ'},
  {location: 'svgsKana/', fname: ' ', name: 'po', jpn: 'ぽ'},
];
